GUI:
  color: "&2&l"
  name: "&8[ &a&lSPY &f&lEDITOR &8]"
  top-row: "&a"
  bottom-row: "&f"

  fail_head: "http://textures.minecraft.net/texture/beb588b21a6f98ad1ff4e085c552dcb050efc9cab427f46048f18fc803475f7"
  fail_name: "&4&lINGEN ADGANG!"
  fail_lore:
    - "&8&m---------------------------"
    - "&7"
    - "&fDu har ikke &cAdmin &fadgang,"
    - "&ftil at se spillere med &espy"
    - "&7"
    - "&8&m---------------------------"

  disable_name: "&c&lDEAKTIVER"
  disable_lore:
    - "&8&m---------------------------"
    - "&7"
    - "&fTryk her for at slå spy &cfra"
    - "&7"
    - "&8&m---------------------------"

  disable_player_lore:
    - "&8&m---------------------------"
    - "&7"
    - "&fTryk her for at slå spy &cfra"
    - "&ffor spilleren &e%player%"
    - "&7"
    - "&8&m---------------------------"

  enable_name: "&a&lAKTIVER"
  enable_lore:
    - "&8&m---------------------------"
    - "&7"
    - "&fTryk her for at slå spy &atil"
    - "&7"
    - "&8&m---------------------------"

Messages:
  reload_success: "&aSuccessfully reloaded"
  reload_failed: "&cError reloading"
  argument_error: "&cArgument ikke fundet!"
  no_permission: "&cIngen adgang!"

  spy: "&e%player% &fbrugte command &6/%command%"

Permissions:
  usage: "spy.use"
  reload: "spy.reload"
  admin: "spy.admin"