name: Spy
version: '${project.version}'
main: dk.nydt.spy.SpyMain
api-version: 1.8
authors: [ Nydt ]
description: Commandspy plugin
website: mcstore.dk
commands:
  spy:
    description: opens spy menu
    aliases: ['cspy', 'commandspy']
